Feature: More phd_exec options

diff --git a/phd_exec.in b/phd_exec.in
--- a/phd_exec.in
+++ b/phd_exec.in
@@ -6,6 +6,8 @@ fi
 
 # Location of current scenario data
 exec_dir="@localstatedir@/lib/phd"
+definition="@sysconfdir@/phd/cluster_definition.conf"
+scenario_dir="@libexecdir@/@PACKAGE@/scenarios"
 
 . ${PHDCONST_ROOT}/lib/transport_ssh.sh
 . ${PHDCONST_ROOT}/lib/phd_utils_api.sh
@@ -18,43 +20,43 @@ function helptext() {
 	echo "phd_exec - A tool for executing pacemaker cluster scenarios"
 	echo "==========================================================="
 	echo ""
-	echo "Usage: phd_exec <cluster definition> <scenario file> [options]"
-	echo "The default behavior when no options are specified is to execute"
-	echo "The scenario file on the given cluster definition"
+	echo "Usage: phd_exec -s <scenario_file> [options]"
+	echo "The default behavior when only the scenario file is provided"
+	echo "is to execute the scenario deployment on the cluster definition"
+	echo "configured in the $defintion file"
 	echo ""
 	echo "Options"
 	echo "-p, --print-env          Print cluster definition environment variables"
+	echo "-s, --scenario           Scenario file name."
+	echo "-l, --list-scenarios     List installed scenario files."
+	echo "-d, --definition         Custom definition file location. Defaults to $definition"
 	echo "-v, --verify-definition  Verify cluster definition can run the scenario file"
-	echo "-t, --run-tests          Run scenario tests after deployment"
-	echo "-l, --log-file           Custom logfile location."
+	echo "-t, --run-tests          Deploy scenario and run scenario tests after deployment."
+	echo "-o, --run-tests-only     Only run tests on deployment." 
+	echo "-f, --log-file           Custom logfile location."
 	echo "-L, --log-level-stdout   Log level 0-4. The higher the level, the more output."
 	echo "-q, --quiet              Keep stdout quiet."
 	echo ""
 	exit $1
 }
 
-definition=$1
-shift
-scenario=$1
-shift
-
-if [ -z "$scenario" ]; then
-	echo "Error: Must provide valid cluster definition and scenario file"
-	echo ""
-	helptext 1
-fi
-
 print_env=0
 check_only=0
 tests=0
 log_file="$exec_dir/phd.log"
+only_tests=0
 while true ; do
 	case "$1" in
 	--help|-h|-\?) helptext 0;;
 	-p|--print-env) print_env=1; shift;;
 	-v|--verify)     check_only=1; shift;;
 	-t|--run-tests)  tests=1; shift;;
-	-l|--log-file)  log_file=$2; shift; shift;;
+	-o|--run-tests-only)  only_tests=1; shift;;
+	-f|--log-file)  log_file=$2; shift; shift;;
+	-d|--definition)  definition=$2; shift; shift;;
+	-s|--scenario)  scenario=$2; shift; shift;;
+	-l|--list-scenarios) ls -1 $scenario_dir
+		exit 0;;
 	-L|--log-level-stdout) phd_set_log_level $2; shift; shift;;
 	-q|--quiet) phd_enable_stdout_log 0; shift;;
 	"") break;;
@@ -64,24 +66,43 @@ done
 
 phd_set_log_file "$log_file"
 phd_set_exec_dir "$exec_dir/phd_scenario"
-
 definition_unpack $definition
-scenario_unpack $scenario
 
+if [ -z "$scenario" ]; then
+	echo "Error: Must provide valid scenario file."
+	echo ""
+	helptext 1
+fi
+
+# Attempt to locate scenario file
+if [ ! -e "$scenario" ]; then
+	scenario="$scenario_dir/$scenario" 
+	if [ ! -e "$scenario" ]; then
+		if [ ! -e "${scenario}.scenario" ]; then
+			echo "Error: Can not find specified scenario file"
+			exit 1
+		fi
+	fi
+fi
+
+scenario_unpack $scenario
 if [ $print_env -eq 1 ]; then
 	print_definition
 	print_scenario
 	exit 0
 fi
-
 if [ $check_only -eq 1 ]; then
 	scenario_verify
 	echo "Success"
 	exit 0
 fi
 
-scenario_exec
+if [ $only_tests -eq 1 ]; then
+	scenario_exec_tests
+	exit $?
+fi
 
+scenario_exec
 if [ $tests -eq 1 ]; then
 	scenario_exec_tests
 fi
